apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'buku-service'
      static_configs:
      - targets: ['buku:80']
      metrics_path: '/actuator/prometheus'

    - job_name: 'cqrs-service'
      static_configs:
      - targets: ['cqrs:80']
      metrics_path: '/actuator/prometheus'

    - job_name: 'eureka'
      static_configs:
      - targets: ['eureka:80']
      metrics_path: '/actuator/prometheus'
