## YAML Template.
---
server:
    port: 9000
    
spring:
    application:
        name: API-GATEWAY-MARKETPLACE
    cloud:
        gateway:
                server:
                    webmvc:
                        routes:
                        - id: PRODUK-SERVICE
                          uri: lb://PRODUK-SERVICE
                          predicates: 
                            - Path=api/produk/**
                        - id: PELANGGAN-SERVICE
                          uri: lb://PELANGGAN-SERVICE
                          predicates: 
                            - Path=api/pelanggan/**
                        - id: ORDER-SERVICE
                          uri: lb://ORDER-SERVICE
                          predicates: 
                            - Path=api/order/**
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost